# Generated by Django 3.2.18 on 2023-03-19 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
